# Generated by Django 4.2.14 on 2024-07-19 04:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('tag', multiselectfield.db.fields.MultiSelectField(choices=[('FU', '장례'), ('CR', '화장'), ('DR', '건조'), ('EN', '봉안')], max_length=11)),
            ],
        ),
    ]
