# Generated by Django 4.2.14 on 2024-07-20 08:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=30, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('tag', multiselectfield.db.fields.MultiSelectField(choices=[('장례', '장례'), ('화장', '화장'), ('건조', '건조'), ('봉안', '봉안')], max_length=11)),
                ('image', models.ImageField(null=True, upload_to='funeralhalls/')),
            ],
        ),
    ]
