# Generated by Django 4.2.14 on 2024-07-19 17:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_petinfo_petanniv_remove_petinfo_petbirth_and_more'),
        ('books', '0003_book_cover_pageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='keyword_tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('위로', '위로'), ('공감', '공감'), ('일상', '일상'), ('편지', '편지')], default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='mind',
            field=models.ManyToManyField(related_name='mind_books', to='accounts.userinfo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_updated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
