# Generated by Django 4.2.14 on 2024-07-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_keyword_tag_book_mind_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_updated',
            field=models.DateField(null=True),
        ),
    ]
