# Generated by Django 4.2.14 on 2024-07-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='keyword_tag',
            field=models.CharField(choices=[('위로', '위로'), ('공감', '공감'), ('일상', '일상'), ('편지', '편지')], max_length=10),
        ),
    ]
