# Generated by Django 4.2.14 on 2024-07-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_last_updated_alter_page_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
