# Generated by Django 4.2.14 on 2024-07-16 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=30)),
                ('petBirth', models.DateField(verbose_name='반려동물 출생일')),
                ('petAnniv', models.DateField(verbose_name='반려동물 사망일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='accounts.userinfo')),
            ],
        ),
    ]
