# Generated by Django 4.2.14 on 2024-07-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_petinfo_petanniv_remove_petinfo_petbirth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petinfo',
            name='pet_image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images'),
        ),
    ]
