# Generated by Django 4.2.14 on 2024-07-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_petinfo_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='petinfo',
            name='pet_type',
            field=models.CharField(choices=[('강아지', '강아지'), ('고양이', '고양이'), ('소동물', '소동물'), ('기타', '기타')], max_length=5, null=True),
        ),
    ]
